services:
  - type: web
    name: learning-log
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "daphne -b 0.0.0.0 -p $PORT learning_log.asgi:application"
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: learning_log.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: learninglog-db
          property: connectionString

databases:
  - name: learninglog-db
    plan: free
