# Generated by Django 5.2.7 on 2025-11-04 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e8403c10-2501-4789-8a13-a93367954bcb'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('eb4aa389-1529-4c94-b209-4f9f685ca0ff'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broadcast.btopic')),
            ],
            options={
                'verbose_name_plural': 'Broadcast Entries',
            },
        ),
    ]
