# Generated by Django 5.2.7 on 2025-11-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_alter_bentry_id_alter_btopic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btopic',
            old_name='text',
            new_name='title',
        ),
    ]
