# Generated by Django 5.2.7 on 2025-11-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_rename_text_btopic_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bentry',
            old_name='owner',
            new_name='btopic',
        ),
    ]
