# Generated by Django 5.2.7 on 2025-11-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0004_rename_owner_bentry_btopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bentry',
            name='text',
            field=models.CharField(max_length=10000000),
        ),
    ]
