# Generated by Django 5.2.7 on 2025-11-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0005_alter_bentry_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bentry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='btopic',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
